server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/pokemicro_auth?useSSL=false&allowPublicKeyRetrieval=true
    username: mpc
    password: mpc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT (usa la misma clave en user-service). Genera un secreto base64 de 256 bits para HS256.
jwt:
  secret-key: "UlduV1Z1R2J2d2tPV2J0YUxkZURsQm1yQUlVaEVzR1Z2b0N6Q1h3Yk9xQ0pTTk5N" # DEV
  expiration-ms: 3600000


# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/